config/routes.rb
ICS::Application.routes.draw do
 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end

  resources :blue_arc_orders
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
    collection do
      delete :empty_carts
      get :cart_details
      post :cart_info
    end

  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite
  get '/services' => "home#services", :as => :services
  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  resources :signatures, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
    end
  end

end

app/views/admins/_latest_orders.html.erb
<div class="tablebox table-newUserAnalytics">
  <div class="row">
    <div class="column">.</div>
  </div>
  <div class="row">
    <ul class="list-latestOrders">
      <% for order in @orders %>
        <li>
          <div class="column-first"><%= link_to (order.id.to_s+' '+order.user.username), ""%></div>
          <div class="column-two">
            <%= order.status == 'Success' ? ("<input class='btn-orange' type='submit' title='PAID' value='PAID' />".html_safe) : ("<input class='btn-blue' type='submit' title='CANCELLED' value='CANCELLED' />".html_safe) %>
          </div>
          <div class="column-three"><%= number_to_currency(order.net_payment)%></div>
        </li>
      <% end %>
    </ul>
    <div class="clearFix"></div>
  </div>
</div>
<span class="pagination" style='float: right;'><%= will_paginate @orders, :param_name => 'latest_order', :next_label => "Next", :previous_label => 'Prev', :page_links => false %></span>
<%= render :partial => '/profiles/pagination_script' %>

app/views/admins/_pending_products.html.erb
<div class="tablebox table-latestProductRequests">
  <div class="row">
    <div class="column">Seller Name</div>
    <div class="column">Product</div>
    <div class="column">Quantity</div>
    <div class="column">Price</div>
    <div class="column">Actions</div>
  </div>
  <% for product in @pending_products %>
    <div class="row">
      <div class="column"><%= product.user.username %></div>
      <div class="column"><%= product.title%></div>
      <div class="column"><%= product.qty %></div>
      <div class="column">$<%= product.price%></div>
      <div class="column">
        <%= link_to_function "<input class='btn-blue' type='submit' title='PAID' value='Confirm' />".html_safe, "preview(#{product.id})", :style => 'text-decoration: none;' %>
      </div>
    </div>
  <% end %>
</div>
<span class="pagination" style='float: right;'><%= will_paginate @pending_products, :param_name => 'pending_product', :next_label => "Next", :previous_label => 'Prev', :page_links => false %></span>
<%= render :partial => '/profiles/pagination_script' %>

app/views/admins/_sales.html.erb
<h1 class="icon-orderSalesManagement"><span>Sales Management</span></h1>
<div class="tablebox table-salesManagement">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Seller Name</div>
    <div class="column">User Name</div>
    <div class="column">Non Profit</div>
    <div class="column">Amount</div>
    <div class="column">Status</div>
  </div>
  <% for order in @orders %>
    <div class="row">
      <div class="column"><%= order.id %></div>
      <div class="column"><%= order.line_item.product.user.username %></div>
      <div class="column"><%= order.user.email %></div>
      <div class="column"><%= order.line_item.product.non_profit_cause.present? ? (order.line_item.product.non_profit_cause) : "-" %></div>
      <div class="column"><%= number_to_currency(order.net_payment) %></div>
      <div class="column last"><%= order.shipping.present? ? (order.shipping) : "In process" %></div>
    </div>
  <% end %>
</div>
<span class="pagination" style='float: right;'><%= will_paginate @orders, :param_name => 'order_page', :next_label => "Next", :previous_label => 'Prev', :page_links => false %></span>
<%= render :partial => '/profiles/pagination_script' %>

app/views/admins/_week.html.erb
<script type="text/javascript" charset="utf-8">
  $(function() {
    Highcharts.setOptions({
      colors: ['#ECA693']
    });
    new Highcharts.Chart({
      chart: {
        renderTo: "container"
      },
      title: {
        text: ""
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        min: 0,
        title: {
          text: "Users"
        }
      },
      tooltip: {
        formatter: function() {
          return Highcharts.dateFormat("%B %e, %Y", this.x) + ': ' +
                  "Count: " + Highcharts.numberFormat(this.y, 0);
        }
      },
      series: [
<% { "Users" => User.where("role != 'admin'")}.each do |name, orders| %>
          {
            name: "<%= name %>",
            pointInterval: <%= 1.day * 1000 %>,
            pointStart: <%= params[:from_date] ? (params[:from_date].to_date.beginning_of_day.to_i * 1000) : (1.month.ago.to_i * 1000) %>,
            data: <%= params[:from_date] ? ("#{orders_chart_series(orders, (params[:from_date].to_date), (params[:to_date].to_date))}") : ("#{orders_chart_series(orders, 1.month.ago, Time.now)}") %>
          },
<% end %>
      ]
    });
  });
</script>

app/views/admins/admin_dashboard.js.erb
$("#latest_orders").html('<%= escape_javascript render :partial => 'latest_orders' %>');
$("#pending_products").html('<%= escape_javascript render :partial => 'pending_products' %>');

app/views/admins/buyer.html.erb
<h1 class="icon-userManagement"><span>User Management</span></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Name</div>
    <div class="column">Email</div>
    <div class="column">Phone</div>
    <div class="column">City</div>
    <div class="column">ZIP</div>
    <div class="column">Country</div>
    <div class="column">Options</div>
  </div>
  <% @users.each_with_index do |user, index| %>
    <div class="row">
      <div class="column"><%= index+1 %></div>
      <div class="column"><%= user.username %></div>
      <div class="column"><%= user.email %></div>
      <div class="column"><%= user.phone.present? ? user.phone : "-" %></div>
      <div class="column"><%= user.city.present? ? user.city : "-" %></div>
      <div class="column"><%= user.zip.present? ? user.zip : "-" %></div>
      <div class="column"><%= user.country.present? ? user.country : "-" %></div>
      <div class="column last">
        <%= user.confirmation_token.nil? ? (link_to "<input class='btn-deActivate' type='submit' title='De Activate' value='Suspend' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Deactive'}, :method => :put, :style => 'text-decoration: none;') : (link_to "<input class='btn-activate' type='submit' title='Activate' value='Approve' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Active'}, :method => :put, :style => 'text-decoration: none;')%>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/non_profit.html.erb
<h1 class="icon-nonProfitManagement"><span>Non-Profit Management</span></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Name</div>
    <div class="column">Email</div>
    <div class="column">Phone</div>
    <div class="column">Total Earning</div>
    <div class="column">Pending</div>
    <div class="column">Option</div>
  </div>
  <% @users.each_with_index do |user, index| %>
    <div class="row">
      <div class="column"><%= index+1 %></div>
      <div class="column"><%= link_to user.username, profile_profile_path(user) %></div>
      <div class="column"><%= user.email %></div>
      <div class="column"><%= user.phone.present? ? user.phone : "-" %></div>
      <div class="column">$699.00</div>
      <div class="column">$400</div>
      <div class="column last">
        <%= user.confirmation_token.nil? ? (link_to "<input class='btn-deActivate' type='submit' title='De Activate' value='Suspend' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Deactive'}, :method => :put, :style => 'text-decoration: none;') : (link_to "<input class='btn-activate' type='submit' title='Activate' value='Approve' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Active'}, :method => :put, :style => 'text-decoration: none;')%>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/products.html.erb
<div id="products">
  <%= render :partial => '/products/index' %>
</div>

app/views/admins/products.js.erb
$("#products").html('<%= escape_javascript render :partial => '/products/index'%>');

app/views/admins/review_product.html.erb
<h1 class="icon-productsManagement"><em class="icon-plus"><%= (user_signed_in? and current_user.role == 'seller') ? (link_to "New Product", new_product_path) : "" %></em><span>Review Product</span></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Product Name</div>
    <div class="column">Posted on</div>
    <div class="column">Price</div>
    <div class="column">Qty Sold</div>
    <div class="column">Qty Remaining</div>
    <div class="column last">Actions</div>
  </div>
  <% @products.each_with_index do |product,index| %>
    <div class="row">
      <div class="column"><%= index+1 %></div>
      <div class="column"><%= link_to product.title, edit_product_path(product) %></div>
      <div class="column"><%= product.created_at.strftime("%Y-%m-%d") %></div>
      <div class="column"><%= number_to_currency(product.price) %></div>
      <div class="column"><%= product.qty_sold %></div>
      <div class="column"><%= product.colors.present? ? (product.colors.first.product_qty) : "--" %></div>
      <div class="column last" style="width: 250px;">
        <%= link_to image_tag("/assets/admin-images/icon-search.png", :class => "icon-search"), product_path(product) %>&nbsp;&nbsp;
        <%= link_to image_tag("/assets/user-images/icon-edit.png", :class => "icon-search"), edit_product_path(product) %>&nbsp;&nbsp;
        <%= link_to image_tag("/assets/user-images/icon-close.png", :class => "icon-search"), product_path(product), :method => :delete, :confirm => "Are you sure." %>
        <%= link_to "<input class='btn-activate' type='submit' title='Activate' value='Approve' />".html_safe, confirm_product_admin_path(product, :status =>'confirmed'), :method => 'put', :class => 'button', :style => 'text-decoration: none;' %>
      </div>
    </div>
  <% end %>
</div>
<span class="pagination" style='float: right;'><%= will_paginate @products, :param_name => 'product_page', :next_label => "Next", :previous_label => 'Prev', :page_links => false %></span>
<%= render :partial => '/profiles/pagination_script' %>
<style>
  .column{
    width: 12%;
  }
</style>

app/views/admins/sales.html.erb
<div id='sales'>
  <%= render :partial => 'sales' %>
</div>

app/views/admins/sales.js.erb
$("#sales").html('<%= escape_javascript render :partial => 'sales'%>');

app/views/admins/seller.html.erb
<h1 class="icon-productsManagement"><span>Seller Management</span></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Seller Name</div>
    <div class="column">Company Name</div>
    <div class="column">Email</div>
    <div class="column">Phone</div>
    <div class="column">Total Sales</div>
    <div class="column">Commission</div>
    <div class="column last">Options</div>
  </div>
  <% @users.each_with_index do |user, index| %>
    <div class="row">
      <div class="column"><%= index+1 %></div>
      <div class="column"><%= user.username %></div>
      <div class="column"><%= user.business_name.present? ? user.business_name : "-"%></div>
      <div class="column"><%= user.email %></div>
      <div class="column"><%= user.phone.present? ? user.phone : "-"%></div>
      <div class="column">$<%= Product.where("products.user_id = #{user.id}").sum {|item| item.price.to_i} %></div>
      <div class="column">$<%= Product.where("products.user_id = #{user.id}").sum {|item| item.price.to_i/10} %></div>
      <div class="column last">
        <%= user.confirmation_token.nil? ? (link_to "<input class='btn-deActivate' type='submit' title='De Activate' value='Suspend' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Deactive'}, :method => :put, :style => 'text-decoration: none;') : (link_to "<input class='btn-activate' type='submit' title='Activate' value='Approve' />".html_safe, {:controller => 'users', :action => 'update', :id => user.id, :role => user.role, :active => 'Active'}, :method => :put, :style => 'text-decoration: none;')%>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/week.js.erb
$('.img-graph-1').html('<%= escape_javascript render :partial => 'week'%>');