config/routes.rb
ICS::Application.routes.draw do
 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end

  resources :blue_arc_orders
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
    collection do
      delete :empty_carts
      get :cart_details
      post :cart_info
    end

  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite
  get '/services' => "home#services", :as => :services
  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  resources :signatures, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  has_many :orders, :dependent => :destroy

  attr_accessible :purchased_at, :created_at, :product_id, :ip_address

 # has_one :order, :dependent => :destroy

  def add_item(product_id, quantity)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += quantity
    else
      current_item = line_items.build(product_id: product_id, quantity: quantity)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:full_price)
  end

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def cart_details
    @cart_detail = CartDetail.new
    #render :layout => false
  end


  def cart_info
    @cart_detail = CartDetail.new(params[:cart_detail])
    if @cart_detail.save
       flash[:success] = "Your information was successfully submited! We will inform you directly  once product is in stack ."
      redirect_to root_path
    else
      render :action  => :cart_details
    end
  end



  def index
    @cart = current_cart
    @user_products = current_cart.line_items
    @order = @cart.orders.new(params[:order])
    @comment = Comment.new
  end
  
  def edit_lineitem
    @line_item = LineItem.find(params[:id])
    @comment = Comment.new
    respond_to do |format|
      format.js
    end
  end
  
  def update_lineitem
    @cart = current_cart
    @user_products = current_cart.line_items
    @order = @cart.orders.new(params[:order])
    @line_item = LineItem.find(params[:id])
    @comment = Comment.new
    if params[:line_item][:quantity].to_i == 0
      @line_item.destroy
      respond_to do |format|
        format.js
      end
    else
      if @line_item.product.qty >= params[:line_item][:quantity].to_i
        @line_item.update_attribute(:quantity, params[:line_item][:quantity])
        respond_to do |format|
          format.js
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end
  end


  def empty_carts
    if current_cart.line_items.present? 
      current_cart.destroy
      session[:cart] = nil
    end
    redirect_to carts_path
  end


  def destroy
    @cart = LineItem.find(params[:id])
    if @cart.destroy
      if !current_cart.line_items.present?
        current_cart.destroy
        session[:cart] = nil
      end
      redirect_to carts_path
    end
  end
  def return
    @notification = Twocheckout::ValidateResponse.purchase({:sid => SID, :secret => SECRET, :order_number => params['order_number'], :total => params['total'], :key => params['key']})

    @cart = Cart.find(params['merchant_order_id'])
    p "******************************"
    p @notification[:code]
    p "*****************************"
    begin
      if @notification[:code] == "PASS"
        @cart.status = 'success'
        @cart.purchased_at = Time.now
        @order = Order.create(
          :net_payment => params['total'],
          :card_holder_name => params['card_holder_name'],
          :status => 'pending',
          :order_number => params['order_number'],
          :cart_id => params['merchant_order_id'],
          :user_id => current_user.present? ? current_user.id : ''
          )
        session[:cart] = nil
        flash[:notice] = "Your order was successful! We will contact you directly to confirm before delivery."
        redirect_to root_url
      else
        @cart.status = "failed"
        flash[:notice] = "Error validating order, please contact us for assistance."
        redirect_to carts_url
      end
    ensure
      @cart.save
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_all_items.html.erb
    <div class="col-main">
      <div class="cart wow bounceInUp animated">
        <div class="page-title">
          <h2>Shopping Cart</h2>
        </div>
        
        <div class="table-responsive">
            <input type="hidden" value="Vwww7itR3zQFe86m" name="form_key">
            <fieldset>
              <table class="data-table cart-table" id="shopping-cart-table">
                <colgroup>
                <col width="1">
                <col>
                <col width="1">
                <col width="1">
                <col width="1">
                <col width="1">
                <col width="1">
                </colgroup>
                <thead>
                  <tr class="first last">
                    <th rowspan="1">&nbsp;</th>
                    <th rowspan="1"><span class="nobr">Product Name</span></th>
                    <!-- <th rowspan="1"></th> -->
                    <th colspan="1" class="a-center"><span class="nobr">Unit Price</span></th>
                    <th class="a-center" rowspan="1">Qty</th>
                    <th colspan="1" class="a-center">Subtotal</th>
                    <th class="a-center" rowspan="1">&nbsp;</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr class="first last">
                    <td class="a-right last" colspan="50">
                    <%= link_to root_path do %>
                      <button onclick="setLocation('<%= root_path %>')" class="button btn-continue" title="Continue Shopping" type="button">
                        <span><span>Continue Shopping</span></span>
                      </button>
                      <% end %>

             <!--    <%#= link_to empty_carts_carts_path, method: :delete do %>
                      <button id="empty_cart_button" class="button btn-empty" title="Clear Cart" value="empty_cart" name="update_cart_action" type="submit">
                        <span><span>Clear Cart</span></span>
                      </button>
                <!--% end %> -->

                    </td>
                  </tr>
                </tfoot>

                <tbody>
              <% @user_products.each do |line_item| %>
                <%= form_tag pay_line_item_orders_path(line_item.id), :method => 'GET', :id => "submit_cart_#{line_item.id}" do %>
                    <tr class="first odd" id="line-item-<%= line_item.id %>">

                      <td class="image">
                      <!-- <a class="product-image" title="Sample Product" href="#/women-s-crepe-printed-black/"> -->
                      <%= image_tag(line_item.product.images.first.image.url(:original), :width => '75', :height => '75', :id => "image_#{line_item.id}", :style => 'cursor: pointer;') %>
                      <!-- </a> -->
                      </td>
                      
                      <td><h2 class="product-name">
                       <a>
                      <%= line_item.product.title %>
                      </a> </h2></td>
                      
                      <!-- <td class="a-center"><a title="Edit item parameters" class="edit-bnt" href="#configure/id/15945/"></a></td> -->
                      
                      <td class="a-right">
                        <span class="cart-price">
                          <span class="price">$</span>
                          <span class="price" id="cart-unit-price-<%= line_item.id %>">
                            <%= number_to_currency(line_item.unit_price, unit: '') %>
                          </span> 
                        </span>
                      </td>
                      
                      <td class="a-center movewishlist">
                        <%= number_field_tag :qty, line_item.quantity, maxlength: "12", id: "cart-qty", class: "input-text qty", title: "Qty", size: '5', min: '1', max: '99', data: { line_item_id: line_item.id } %>
                      </td>

                      <td class="a-right movewishlist" id="line-item-sub-total">
                        <span class="cart-price">
                          <span class="price" id="lineitem-subtotal">
                            <%= number_to_currency(line_item.unit_price.to_f * line_item.quantity.to_i) %>
                          </span>
                        </span>
                      </td>

                      <td class="a-center last">
                      <%= link_to "<span><span>Remove item</span></span>".html_safe, cart_path(line_item), :method => :delete, :confirm => "Are You Sure", :class => "button remove-item" %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
                </tbody>
              </table>
            </fieldset>
        </div>
        <!-- BEGIN CART COLLATERALS -->
        <div class="cart-collaterals row">
          
         
        <div class="totals col-sm-4">
          <h3>Shopping Cart Total</h3>
          <div class="inner">
            <table class="table shopping-cart-table-total" id="shopping-cart-totals-table">
              <colgroup>
              <col>
              <col width="1">
              </colgroup>
              <tfoot>
                <tr>
                  <td colspan="1" class="a-left" style=""><strong>Grand Total</strong></td>
                  <td class="a-right" style=""><strong><span class="price"><%= number_to_currency(@cart.total_price) %></span></strong></td>
                </tr>
              </tfoot>
              <!-- <tbody>
                <tr>
                  <td colspan="1" class="a-left" style=""> Subtotal </td>
                  <td class="a-right" style=""><span class="price">$77.38</span></td>
                </tr>
              </tbody> -->
            </table>
            <ul class="checkout">
              <li>
                <button onclick="window.location='/carts/cart_details';" class="button btn-proceed-checkout" title="Proceed to Checkout" type="button"><span>Proceed to Checkout</span></button>
                
              </li>
              <br>
  
              <br>
            </ul>
          </div>
          <!--inner--> 
          
        </div>
      </div>
      
      <!--cart-collaterals--> 
      
    </div>
    
  </div>

<!-- End Footer -->

app/views/carts/_carts.html.erb
<h1 class="icon-productsManagement"></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">Image</div>
    <div class="column">Item Total</div>
    <div class="column">Full Price</div>
    <div class="column">Qty</div>
    <div class="column">Pay</div>
    <div class="column last">Cancel</div>
  </div>
  <% for line_item in @user_products %>
    <div class="row">
      <div class="column"><%= image_tag(line_item.product.images.first.image.url(:original), :width => '50', :height => '50', :id => "image_#{line_item.id}", :style => 'cursor: pointer;') %></div>
      <div class="column"><%= number_to_currency(line_item.full_price) %></div>
      <div class="column"><%= number_to_currency(line_item.full_price) %></div>
      <div class="column"><%= line_item.quantity %></div>
      <div class="column">
        <%= link_to "Proceed to Checkout", line_item_orders_path(line_item.id), :method => 'POST', :style => 'text-align: center;' %>
      </div>
      <div class="column last">
        <%= link_to "Close", cart_path(line_item), :method => :delete, :confirm => "Are You Sure" %>
      </div>
    </div>
  <% end %>
</div>

app/views/carts/_commons.html.erb
<div class="col-item">
  <div class="product-image-area">
  <% if product.images.present? %>
   <a class="product-image" title="Sample Product" href=<%= product_path(product)%>> 
  
            <%= image_tag(product.images.first.image.url(:original), :width => "#{90}", :height => "#{90}") %>
   </a>
   <% end %>
  </div>

  <div ><span class="add-to-links"> <a title="magik-btn-quickview" class="magik-btn-quickview" href=<%= product_path(product)%>><span>quickview</span></a></span> </div>

  <div class="info">
    <div class="info-inner">
      <div class="item-title"> <a title=" Sample Product" href=<%= product_path(product)%>> <%= product.title %> </a> </div>
      <!--item-title-->
      <div class="item-content">
        <div class="price-box">
          <p class="special-price"> <span class="price"> <%= number_to_currency(product.price) %> </span> </p>
        </div>
      </div>
      <!--item-content--> 
    </div>
    <!--info-inner-->
    <div class="actions">
      <%= link_to '<button type="button" title="Add to Cart" class="button btn-cart"><span>Add to Cart</span></button>'.html_safe, add_to_cart_product_path(product, :qty => 1)%>
    </div>
    <!--actions-->
    
    <div class="clearfix"> </div>
  </div>
</div>

app/views/carts/_edit_lineitem.html.erb
<%= form_for @line_item, :url => update_lineitem_cart_path(@line_item), :method => 'PUT', :html => {:id => "search-query"}, :remote => true do |f| %>
  <%= f.text_field :quantity, :style => 'width: 10px;' %>
  <%= f.submit "Add" %>
<% end %>

app/views/carts/_index.html.erb
<div class="page">
  <section class="main-container col1-layout">
    <div class="main container">
    <% if @user_products.present? %>
    <div class="content">
      <div id='all_items'>
        <%= render :partial => 'all_items'%>
      </div>
    </div>
    <% else %>
    	<div class="col-sm-6"><b>There are no items in this cart.</b></div> 
      <img alt="Cart" src="/assets/cart2.png" height="30.3%" width="30.3%">
    <% end %>
    </div>
  </section>
</div>

app/views/carts/_payment.html.erb
<% @params = {'sid' => SID, 'mode' => '2CO', 'merchant_order_id' => current_cart.id} %>


<% i=0 %>
<% for line_item in current_cart.line_items %>
    <% @params['li_'+i.to_s+'_product_id'] = line_item.product.id.to_s %>
    <% @params['li_'+i.to_s+'_name'] = line_item.product.title %>
    <% @params['li_'+i.to_s+'_price'] = line_item.product.price %>
    <% @params['li_'+i.to_s+'_quantity'] = line_item.quantity.to_s %>
    <% i+=1 %>
<% end %>

<% @form = Twocheckout::Checkout.form(@params, "Checkout with 2Checkout") %>
<%p @form %>
<%= @form.html_safe %>

app/views/carts/_products.html.erb
<div>
  <h4><%= product.title.truncate(50, separator: ' ') %></h4>
  <p>Seller: <%= link_to product.sell_name.present? ? product.sell_name.truncate(22) : product.user.username.truncate(22), seller_path(product.user.id) %></p>
  <span><%= number_to_currency(product.price) %></span>
  <!-- <div class="offer"><%#= product.non_profit_percentage %><%= "%" %></div> -->
</div>
<%= link_to "<input type='submit' title='More Info' value='More Info' />".html_safe, product_path(product), :style => 'text-decoration: none;' %>
<%= link_to "<input type='submit' title='Add To Cart' value='Add To Cart' />".html_safe, add_to_cart_product_path(product, :qty => 1), :style => 'text-decoration: none;' %><br /><br /><br />

app/views/carts/cart_details.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3">
    <div class="panel-heading">
  <h5> Sorry the selected Product is not avialable in the stock.</h5>
  <h5> Please give us your details.We
will inform you once the product is in the Stock </h5>
    </div>
  <%= form_for @cart_detail, :url => cart_info_carts_path, :method => "POST"  do |f| %>
       <div class="panel-body">

  <% if @cart_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_detail.errors.count, "error") %> prohibited your details from being saved:</h2>

      <ul>
      <% @cart_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div><br/>

  <div class="field">
    <%= f.label :Email %><br>
    <%= f.email_field :email %>
  </div><br/>


   <div class="field">
    <%= f.label :Phone %><br>
    <%= f.text_field :phone_no %>
  </div>
<br/>

  <div class="actions">
    <%= f.submit "Send Details", :class => "btn btn-default" %>
  </div>
  </div>
<% end %>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
</div>

<style>


#error_explanation {
  color: #f00;
   border: 1px solid #CCC;
   margin-bottom: 20px;
   padding: 10px;
  ul {
    list-style: none;
    margin: 0 0 18px 0;
  }
}

.field_with_errors {
  padding: 1px;
  background-color: #f00;
  display: table;
}

</style>

app/views/carts/edit_lineitem.js.erb
$('#qua').hide();
$('#line_item_quantiy_<%= @line_item.id %>').html('<%= escape_javascript render :partial => 'carts/edit_lineitem' %>');

app/views/carts/index.html.erb
<%= render :partial => 'index' %>

app/views/carts/update_lineitem.js.erb
$("#all_items").html('<%= escape_javascript render :partial => 'carts/all_items'%>');