config/routes.rb
ICS::Application.routes.draw do
 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end

  resources :blue_arc_orders
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
    collection do
      delete :empty_carts
      get :cart_details
      post :cart_info
    end

  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite
  get '/services' => "home#services", :as => :services
  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'

  resources :signatures, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title,:promotion_code_id,:product_ability,:cause_id,:fair_trade,:non_profit_cause, :color,:shipping, :sell_name, :user_id,:status,:agree_terms, :description, :price, :colors_attributes, :images_attributes, :shipping_products_attributes,:category_id,:discount,:qty, :qty_sold, :non_profit_percentage, :cause_sub_category, :reject_message, :sub_category_id, :sub_sub_category_id, :product_color
  belongs_to :user
  belongs_to :category
  belongs_to :cause
  has_many :images, :dependent => :destroy
  has_many :comments, :as => :commentable
  has_many :colors, :dependent => :destroy
  has_many :shipping_products, :dependent => :destroy
  has_many :share_products, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :billing_shipping_addresses, :dependent => :destroy
  has_one :favourite, :dependent => :destroy
  validates :shipping, :presence => true, :on => :create
  validates :title, :sell_name,:agree_terms, :description,:category_id, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 1}, :presence => true
  validates_numericality_of :qty, :greater_than_or_equal_to => 1
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :shipping_products,  :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :colors, :allow_destroy => true, :reject_if => :all_blank

  def to_param
    "#{id} #{title}".parameterize
  end
  
  def self.import(file,user_id)
    CSV.foreach(file.path) do |row|
      product = Product.new(:user_id => user_id,:status => 'pending',:title => row[0], :price => row[1], :images_attributes => {"0" => {:image => row[2]}}) 
      product.save(:validate => false)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :is_signin?, :only => ['index','new','create','preview_product','review','product_review']
  before_filter :is_valid_account? , :only => ['index','new','create']

  def index
    @products = Product.where("user_id = #{current_user.id}").order('product_count DESC').paginate :page => params[:product_page], :per_page => 10 if (user_signed_in? and (current_user.role == 'seller' || current_user.role == 'admin'))
  end
  
  def import
  end
  
  def upload_products
    if request.post? && params[:file].present?
      Product.import(params[:file],current_user.id)
      redirect_to products_path
    else
      flash[:error] = "Failed to Upload a file"
      render :action => 'import'
    end
  end

  def new
    @product = Product.new
    1.times {@product.images.build}
    1.times {@product.colors.build}
    1.times {@product.shipping_products.build}
  end
  
  def categories
    @categores = SubCategory.where("category_id = #{params[:id]}")
    respond_to do |format|
      format.js
    end
  end
  
  def sub_categories
    p "*********************************"
    p params[:sub_category_id]
    @sub_categories = SubSubCategory.where(sub_category_id: params[:sub_category_id])
    p "*********************************"
    puts @sub_categores.inspect
    respond_to do |format|
      format.js
    end
  end

  def create
    @product = Product.new(params[:product].merge(:user_id => current_user.id))
    @product.status = 'pending'
    @product.non_profit_cause = params[:non_profit_cause]
    @product.cause_id = params[:cause_id] if params[:cause_id].present?
    @product.category_id = params[:category_id] if params[:category_id].present?
    @product.sub_category_id = params[:sub_category_id] if params[:sub_category_id].present?
    @product.sub_sub_category_id = params[:sub_sub_category_id] if params[:sub_sub_category_id].present?
    1.times { @product.images.build } if @product.images.blank?
    1.times { @product.colors.build } if @product.colors.blank?
    1.times {@product.shipping_products.build} if @product.shipping_products.blank?
    if @product.save
      #@product.post
      flash[:success] = "Successfully create the project."
      redirect_to products_path
    else
      flash[:error] = "Failed to create the project."
      render :action => 'new'
    end
  end
  
  def create_comment
    @cart = current_cart
    @user_products = current_cart.line_items
    @order = @cart.orders.new(params[:order])
    @product = Product.find(params[:id])
    @line_item = LineItem.find(params[:line_item_id])
    @comment = @product.comments.new(params[:comment])
    if @comment.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  def reject
    @product = Product.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def show
    @product = Product.find(params[:id])
    @category = Category.find(@product.category_id)
    ShareProduct.destroy_all
    @reviews = @product.reviews.paginate :page => params[:review_page], :per_page => 5
  end
  
  def sort_review
    @product = Product.find(params[:id])
    if params[:sort] == 'highest'
      @reviews = @product.reviews.order("rating Desc").paginate :page => params[:review_page], :per_page => 10
    elsif params[:sort] == 'lowest'
      @reviews = @product.reviews.order("rating Asc").paginate :page => params[:review_page], :per_page => 10
    else
      @reviews = @product.reviews.order("created_at #{params[:sort]}").paginate :page => params[:review_page], :per_page => 10
    end
    render :partial => 'total_reviews', :layout => false
  end
  
  def cause_types
    @photos = Cause.where("cause_type = '#{params[:cause_type]}' OR cause_type = 'Any'")
    render :partial => 'cases', :layout => false
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.non_profit_cause = params[:non_profit_cause]
    @product.cause_id = params[:cause_id] if params[:cause_id].present?
    @product.category_id = params[:category_id] if params[:category_id].present?
    if @product.update_attributes(params[:product])
      @product.update_attribute(:color, 'Modify')
      flash[:success] = "Successfully updated the Product."
      redirect_to products_path if(current_user.role == 'seller' || current_user.role == 'admin')
     # redirect_to products_admins_path if current_user.role == 'admin'
    else
      flash[:error] = "Fail to update product"
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path if current_user.role == 'seller'
    redirect_to products_admins_path if current_user.role == 'admin'
  end

  def search
    if params[:from].present? and params[:to].present?
      @products = Product.where("status = 'confirmed' and (price BETWEEN #{params[:from]} AND #{params[:to]})")
    else
      @products = Product.where("status = 'confirmed' and title = '#{params[:query]}'")
    end
  end
  
  def add_to_cart
    @cart = current_cart
    @product = Product.find(params[:id])
    @cart.update_attributes({
        :created_at => Time.now
      })
    @line_item = @cart.add_item(@product.id, params[:qty].to_i)
    @line_item.unit_price = @product.price
    @line_item.status = params[:colour] if params[:colour].present?
    session[:cart] = @cart.id
    if @product.qty >= @line_item.quantity
      @line_item.save
    else
      flash[:error] = "Only #{@product.qty} left in stock"
    end
    redirect_to carts_path
  end

  def preview_product
    @product = Product.find(params[:id])
    render :layout => false
  end
  
  def review
    @product = Product.find(params[:id])
    @review = @product.reviews.new
  end
  
  def product_review
    @product = Product.find(params[:id])
    @review = @product.reviews.new(params[:review].merge(:user_id => current_user.id))
    if @review.save
      flash[:success] = "Succefully given the review to this product"
      redirect_to product_path(@product)
    else
      flash[:error] = "Failed to review the product"
      render :action => 'review'
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cases.html.erb
<%= select_tag :cause_id, options_for_select([["Select",""]]+@photos.map{|c| [c.title, c.id]}, params[:cause_id]) %>

app/views/products/_form.html.erb
<table width="100%">
  <tr class="row">
    <td>Seller Name</td>
    <td><%= f.text_field :sell_name %></td>
  </tr>
  <tr class="row">
    <td><%= f.label :category_id, "Product Category:#{mark}".html_safe %></td>
    <td><%= select_tag :category_id, options_for_select([["Select",""]]+Category.where("parent_id IS NULL").collect{|a| [a.name.capitalize, a.id]}, :selected => f.object.category_id), :onchange => 'select_file(this.value)' %></td>
  </tr>
  <tr class="row">
    <td></td>
    <td id="category"></td>
  </tr>
  <tr class="row">
    <td><%= f.label :title, "Product Name:#{mark}".html_safe %></td>
    <td><%= f.text_field :title %></td>
  </tr>
  <tr class="row">
    <td valign="top">Add Attributes:<%= "#{mark}".html_safe %></td>
    <td>
      <%= f.fields_for :colors do |builder| %>
        <div>
          <%= builder.text_field :product_color, :placeholder => 'Color', :style => 'width: 134px;'  %>
          <%= builder.text_field :size, :placeholder => 'Size', :style => 'width: 134px;' %>
          <%= builder.text_field :buyer_type, :placeholder => 'Type: Male/Female', :style => 'width: 134px;' %>
          <%= builder.link_to_remove image_tag("/assets/seller-images/icon-close.png"), 'data-nested-form-disable-first' => '' %>
        </div>
      <%end%>
      <div id="add_color">
        <%= f.link_to_add "<span style='color: red;'>Add Attributes</span>".html_safe, :colors %>
      </div>
    </td>
  </tr>
<!--   <tr class="row">
    <td>Fair Trade</td>
    <td><%= f.radio_button :fair_trade, "Yes" %>Yes
      <%= f.radio_button :fair_trade , "No"%>No</td>
  </tr>
  <tr class="row">
    <td></td>
    <td>
      <%= f.check_box :product_ability %>Hide Product</td>
  </tr> -->
  <tr class="row">
    <td>Quantity</td>
    <td><%= f.text_field :qty %></td>
  </tr>
  <tr class="row">
    <td><%= f.label :price, "Price:#{mark}".html_safe %></td>
    <td><%= f.text_field :price %></td>
  </tr>
  <%# if @product.new_record? || @product.images.blank? %>
    <tr class="row">
      <td valign="top">Images:<%= "#{mark}".html_safe %></td>
      <td>
        <%= f.fields_for :images do |builder| %>
          <%= builder.file_field :image  %>
          <%= builder.link_to_remove image_tag("/assets/seller-images/icon-close.png"), 'data-nested-form-disable-first' => '' %>
        <%end%>
        <div>
          <%= f.link_to_add "<span style='color: red;'>Add More Images</span>".html_safe, :images %>
        </div>
        <br />
      </td>
    </tr>
  <%# end %>
<!--   <tr class="row">
    <td><%= f.label :non_profit_cause, "Select Cause Category:#{mark}".html_safe %></td>
    <td>
      <%= select_tag :non_profit_cause, options_for_select([["Select Cause Category",""], ["Animal Cause", 'Animal Cause'], ["Human Cause", "Human Cause"],["Enivronmental Cause","Environmental Cause"],["Any","Any"]], :selected => f.object.non_profit_cause), :onchange=>"cause_type(this.value)" %>
    </td>
  </tr> -->
<!--   <tr class="row">
    <td><%= f.label :cause_id, "Support Cause:" %></td>
    <td>
      <div id="client-category">
        <%= select_tag :cause_id, options_for_select(["Select",""], :selected => f.object.cause_id) %>
      </div>
    </td>
  </tr> -->
  <tr class="row">
    <td><%= f.label :promotion_code_id, "Promotion Code:" %></td>
    <td>
      <div id="client-category">
        <%= f.select :promotion_code_id, options_for_select([["Select",""]]+PromotionCode.all.map{|a| [a.promo_code, a.id]}, :selected => f.object.cause_id) %>
      </div>
    </td>
  </tr>
<!--   <tr class="row">
    <td><%= f.label :non_profit_percentage, "Percentage to Non-Profit:#{mark}".html_safe %></td>
    <td><%= f.text_field :non_profit_percentage %></td>
  </tr> -->
  <tr class="row">
    <td><%= f.label :description, "Description:#{mark}".html_safe %></td>
    <td><%= f.text_area :description, :cols => 33, :rows => 3 %></td>
  </tr>
  <tr>
    <td valign="top">Shipping Details:<%= "#{mark}".html_safe %></td>
    <td><%= f.text_field :shipping, :placeholder => "Estimate Shipping Time" %></td>
  </tr>
  <tr class="row">
    <td></td>
    <td>
      <span style="position: relative;font-weight: bold;">Ships To</span>
      <span style="position: relative;left: 111px;font-weight: bold;">Cost</span>
      <span style="position: relative;left: 175px;font-weight: bold;"> With another item ?</span>
      <%= f.fields_for :shipping_products do |builder| %>
        <div>
          <span id="cc"><%= builder.country_select :country, ["United States"] %></span>
          <%= builder.select :location, %w($ र €), :style => 'width: 50px;' %>
          <%= builder.text_field :cost, :placeholder => "Shipping Cost", :style => 'width: 75px;' %>
          <%= builder.text_field :item_cost, :placeholder => "Each Item Cost", :style => 'width: 80px;' %>
          <%= builder.link_to_remove image_tag("/assets/seller-images/icon-close.png"), 'data-nested-form-disable-first' => '' %>
        </div>
      <%end%>
      <style>
        #cc select{
          width: 100px;
        }
      </style>
      <div>
        <%= f.link_to_add "<span style='color: red;'>Add Location</span>".html_safe, :shipping_products  %>
      </div>
      <br />
    </td>
  </tr>
  <tr class="row">
    <td></td>
    <td><%= f.check_box :agree_terms %><%= "#{mark}".html_safe %>The products listed on the site and are not selling items not allowed to sell on HandiCraft Studios, etc.</td>
  </tr>
  <tr class="row">
    <td></td>
    <td>
      <div><img alt="" title="" src="/assets/user-images/spacer.png" /></div>
      <div><input type="submit" title="Submit" value="Submit for Review" /></div>
    </td>
  </tr>
</table>
<script>
  function cause_type(val) {
    $.ajax({
      url: '/products/cause_types?cause_type=' + val,
      success: function(data) {
        $("#client-category").html(data);
      }
    });
  }

  function select_file(val) {
    $.ajax({
      url: '/products/categories?id=' + val
    });
  }
</script>

app/views/products/_index.html.erb
<h1 class="icon-productsManagement"><em class="icon-plus"><%= (user_signed_in? and (current_user.role == 'seller' || current_user.role == 'admin')) ? (link_to "New Product", new_product_path) : "" %></em><span>Product Mangement</span></h1>

<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">ID</div>
    <div class="column">Product Name</div>
    <div class="column">Posted on</div>
    <div class="column">Price</div>
    <div class="column">Qty Sold</div>
    <div class="column">Qty Remaining</div>
    <div class="column">Status</div>
    <div class="column last">Actions</div>
  </div>
  
  <% @products.each_with_index do |product,index| %>
    <div class="row">
      <div class="column"><%= index+1 %></div>
      <div class="column"><%= link_to product.title, edit_product_path(product) %></div>
      <div class="column"><%= product.created_at.strftime("%Y-%m-%d") %></div>
      <div class="column"><%= number_to_currency(product.price) %></div>
      <div class="column"><%= product.qty_sold %></div>
      <div class="column"><%= product.qty %></div>
      <div class="column"><%= product.status %></div>
      <div class="column last">
        <%= link_to image_tag("/assets/admin-images/icon-search.png", :class => "icon-search"), product_path(product) %>&nbsp;&nbsp;
        <%= link_to image_tag("/assets/user-images/icon-edit.png", :class => "icon-search"), edit_product_path(product) %>&nbsp;&nbsp;
        <%= link_to image_tag("/assets/user-images/icon-close.png", :class => "icon-search"), product_path(product), :method => :delete, :confirm => "Are you sure." %>
        <%= current_user.role == 'seller' ? (link_to "Images", product_images_path(product)) : " " %>
      </div>
    </div>
  <% end %>
</div>
<span class="pagination" style='float: right;'><%= will_paginate @products, :param_name => 'product_page', :next_label => "Next", :previous_label => 'Prev', :page_links => false %></span>
<%= render :partial => '/profiles/pagination_script' %>
<style>
  .column{
    width: 12%;
  }
</style>

app/views/products/_login_show.html.erb
<h1 class="icon-productsManagement"><span>Product Details</span></h1>
<div class="content-profile content-productDetails">
  <div class="commonrow">
    <div class="productDetails-leftColumn"><div class="midSec"><%= image_tag(@product.images.first ? @product.images.first.image.url(:original) : "no_image.gif", :width => '450px', :height => '350px', :style => 'border-radius: 5px;') %></div><br />
      <div class="leftSec" style="max-height: 400px;overflow: auto;">
        <% if !@product.images.blank? %>
          <% for image in @product.images %>
            <%= link_to image_tag(image.image.url(:original), :width => "70", :height => "70", :style => 'border-radius: 5px;'), "#" %>
          <% end %>
        <% else %>
          <%= image_tag("no_image.gif", :width => "20") %>
        <% end %>
      </div>
    </div>
    <div class="productDetails-rightColumn">
      <h2><%= @product.title %><br /><span><%= number_to_currency(@product.price) %></span></h2>
      <% if current_user.role == 'buyer' %>
        <div class="icon-addCart">
          <%= link_to "ADD TO CART", add_to_cart_product_path(@product) %>
        </div>
      <% end %>
      <p><%= @product.description %></p>
    </div>
  </div>
</div>

app/views/products/_no_login.html.erb
 <section class="main-container col1-layout">
    <div class="main container">
      <div class="col-main">
        <div class="row">
          <div class="product-view">
            <div class="product-essential">
                <input name="form_key" value="6UbXroakyQlbfQzK" type="hidden">
                <div class="product-img-box col-sm-5 wow bounceInRight animated">
                  
                    <div class="large-image">
                     <a href=<%= @product.images.first.image.url(:original) %> > 
                     <%= image_tag(@product.images.first.image.url(:original)) %> 
                    </a> 
                    </div>

                    <div class="flexslider flexslider-thumb">
                      <ul class="previews-list slides">
                      <% if !@product.images.blank? %>
                        <% for image in @product.images %>
                        <li>
                          <a href=<%= image.image.url(:original) %> class='cloud-zoom-gallery' rel="useZoom: 'zoom1', smallImage: '<%= image.image.url %>' ">
                          <%= image_tag(image.image.url(:original)) %>
                          </a>
                        </li>
                        <% end %>
                      <% end %>
                      </ul>
                    </div>
                  </div>
                  
                  <!-- end: more-images -->
                  
                  <div class="clear"></div>
                </div>
                <div class="product-shop col-sm-7 wow bounceInLeft animated">
                  <div class="product-next-prev"> <a class="product-next" href="#"><span></span></a> <a class="product-prev" href="#"><span></span></a> </div>
                  <div class="product-name">
                    <h1><%= @product.title %></h1>
                  </div>
                 
                <!--   <p class="availability in-stock"><span>In Stock</span></p> -->
                  <div class="price-block">
                    <div class="price-box">
                
                      <p class="special-price"> <span class="price-label">Special Price</span> <span class="price"> <%= number_to_currency(@product.price) %> </span> </p>
                    </div>
                  </div>
                  <div class="short-description">
                    <h2>Quick Overview</h2>
                    <p><%= @product.description %></p>
                  </div>

              <%= form_tag add_to_cart_product_path(@product), :method => 'get' do %>
                  <div class="add-to-box">
                    <div class="add-to-cart">
                      <label for="qty">Quantity:</label>
                      <div class="pull-left">
                        <div class="custom pull-left">
                        <%= text_field_tag :qty, "1", class: "input-text qty", maxlength: "12", id: "qty" %>
                          <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;" class="increase items-count" type="button"><i class="icon-plus">&nbsp;</i></button>
                          <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 0 ) result.value--;return false;" class="reduced items-count" type="button"><i class="icon-minus">&nbsp;</i></button>
                        </div>
                      </div>
                      <div class="pull-left">
                        <% unless (current_user and current_user.role == 'seller') %>
                          <button class="button btn-cart" title="Add to Cart" type="submit"><span><i class="icon-basket"></i> Add to Cart</span></button>
                        <% end %>
                      </div>
                    </div>      
                  </div>
                <%end%>
                </div>
              
            </div>
            <!-- <div class="product-collateral"> -->
              <div class="col-sm-12 wow bounceInUp animated">
                <ul id="product-detail-tab" class="nav nav-tabs product-tabs">
                  <li class="active"> <a href="#product_tabs_description" data-toggle="tab"> Product Description </a> </li>
                               </ul>
                <div id="productTabContent" class="tab-content">
                  <div class="tab-pane fade in active" id="product_tabs_description">
                    <div class="std">
                      <p><%= @product.description %></p> 
                    </div>
                  </div>
              </div>
              <div class="col-sm-12">
                <div class="box-additional">
                  <div class="related-pro wow bounceInUp animated">
                    
                  </div>
                </div>
              </div>
           <!--  </div> -->
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/products/_total_reviews.html.erb
<span style="position: relative;width: 75px;">Sort by: <%= select_tag :sort, options_for_select([["Select", ""],["Most Recent","Desc"],["Highest Rating", "highest"],["Lowest Rating", "lowest"]], params[:sort]), :onChange => "client_logos(#{@product.id}, this)" %></span>
<span style="position: relative;float: right; width: 75px;"><%= will_paginate @reviews, :param_name => 'review_page', :page_links => false, :previous_label => "PREV", :next_label => "NEXT" %></span>
<hr />
<% for review in @reviews %>
  <table width="100%;" style="line-height: 25px;">
    <tr>
      <td>
        <div id="stars-rating">
          <div class="stars-<%=h review.rating.html_safe %> ratings"></div>
        </div>
      </td>
      <td></td>
      <td><b><%= review.name %></b></td>
    </tr>
    <tr>
      <td>
        <b><%= review.title %></b> - <%= review.created_at.strftime("%d/%m/%Y") %>
      </td>
    </tr>
    <tr>
      <td>
        <p style="width: 800px;"><%= review.message %></p>
      </td>
    </tr>
  </table>
<% end %>
<hr />
<div style="position: relative; left: 930px; width: 75px;">
  <%= will_paginate @reviews, :param_name => 'review_page', :page_links => false, :previous_label => "PREV", :next_label => "NEXT" %>
</div>
<hr />
<script>
  $(function() {
    $(".pagination a").click(function() {
      $.getScript(this.href);
      return false;
    });
  });
</script>

app/views/products/create_comment.js.erb
<% if @comment.errors.present? %>
  $("#all_items").html('<%= escape_javascript render :partial => 'carts/all_items' %>');
  $("#error_comment_<%=@line_item.id%>").show();
<% else %>
  $("#all_items").html('<%= escape_javascript render :partial => 'carts/all_items' %>');
  $("#success_comment_<%=@line_item.id%>").show();
<% end %>

app/views/products/edit.html.erb
<h1 class="icon-addProduct"><span>Add Product</span></h1>
<%= render :partial => '/layouts/error_messages', :locals => {:resource => @product} %>
<div class="content-profile">
  <%= nested_form_for @product, :url => product_path(@product), :method => "PUT" do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/products/import.html.erb
<h1 class="icon-profile"><span>Import Products</span></h1>
<div class="content-profile">
  <div id="formDiv">
    (Format required of the import should be <b>Product Title, Price, Seller Name</b>)<br />
    <b style="color: red;font-size: 13px;">Hint: (Presently working this issue don't upload any csv file)</b>
    <%= form_tag upload_products_products_path, :multipart => true do %>
      <table>
        <tr class="row">
          <td>Product CSV File:</td>
          <td><%= file_field_tag :file %></td>
        </tr>
        <tr class="row">
          <td></td>
          <td>
            <div><input type="submit" title="Submit" value="Submit" /></div>
          </td>
        </tr>
      </table>
    <%end%>
  </div>

app/views/products/index.html.erb
<div id='products'>
  <%= render :partial => 'index' %>
</div>

app/views/products/reject.js.erb
$("#reject").html('<%= escape_javascript render :partial => 'reject' %>');

app/views/products/show.html.erb
<%= current_user && current_user.role == 'admin' ? (render :partial => '/products/login_show') : (render :partial => '/products/no_login') %>

app/views/products/show.js.erb
$("#tot_reviews").html('<%= escape_javascript render :partial => 'total_reviews' %>');

app/views/products/sub_categories.js.erb
<% if @sub_categories.present? %>
  $("#sub_category").html('<%= escape_javascript render :partial => 'sub_categories' %>');
<% else %>
  $("#sub_category").hide();
<% end %>